In [24]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)  #5, denotes that its 1d array having 5 rows

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
b=np.array([[1,2,3],[4,5,6]])  # THIS IS KIND OF 2D ARRAY
print(b)
print()
print(b.shape)
print(b[1][1])

[[1 2 3]
 [4 5 6]]

(2, 3)
5


# CREATING CUSTOM ARRAYS OF ZEROS , ONES AND OTHER CHOICES

In [17]:
c=np.zeros((3,3))
print(c)
print(type(c))

b=np.ones((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
c= np.full((3,2),5)  # CREATING CUTOM ARRAY
print(c)

[[5 5]
 [5 5]
 [5 5]]


# CREATING IDENTITY MATRIX


In [19]:
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# RANDOM MATRIX

In [22]:
ran = np.random.random((2,3))
print(ran)

[[0.91541599 0.32136891 0.41142978]
 [0.03352637 0.13325498 0.43119721]]


In [24]:
print(ran[ : ,1]) #THIS WILL PRINT ALL THE ELEMENTS OF 1ST COLUMN

[0.32136891 0.13325498]


In [27]:
ran[1,1:3] = 1 #THIS WOULD UPDATE THE 1ST ROW'S 1ST AND 2ND ELEMENT ELIMINATING THE 3RD ONE
print(ran)

[[0.91541599 0.32136891 0.41142978]
 [0.03352637 1.         1.        ]]


In [31]:
ran[1,:] = 5
print(ran)
print()
print()
ran[ :,-1] = 7
print(ran)

[[0.91541599 0.32136891 7.        ]
 [5.         5.         5.        ]]


[[0.91541599 0.32136891 7.        ]
 [5.         5.         7.        ]]


# ALL numpy ARRAY HAS SOME DATATYPE 

In [33]:
print(ran.dtype)

float64


In [37]:
#ELEMENT WISE ADDDITION 
x = np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print()
print(x*y)
print(np.multiply(x,y))
print()
print(x/y)
print(np.divide(x,y))
print()
print(np.sqrt(x))
print()
print(np.sqrt(y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


# MATRIX MULTIPLICATION / DOT PRODUCT , DOT PRODUCT OF TWO VECTORS WILL GIVE US A SCALAR

In [86]:
x=np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(y))
print()
print(np.dot(x,y))

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print("\n")
print(a.dot(b))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


30


In [41]:
print(sum(a))

15


In [44]:
print(np.sum(x,axis=0)) # AXIS = 0 PARAMETER WILL SUM ALONG THE COLUMNS , AXIS = 1 WILL GIVE SUM ALONG THE ROW
print(np.sum(x,axis=1))

[4 6]
[3 7]


# STACKING OF ARRAYS , IMPORTANT FOR ML

In [102]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
b = b**2
print(b)


[1 2 3 4]
[ 1  4  9 16]


In [103]:
print(np.stack((a,b),axis = 0))
print()
print(np.stack((a,b),axis = 1))

[[ 1  2  3  4]
 [ 1  4  9 16]]

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [104]:
a = np.stack((a,b),axis =0)
a=a.reshape((4,2)) # IF WE PUT 4,-1 OR -1,4 THEN IT WILL AUTOMATICALLY FIGURE OUT HOW MUCH ROWS AND COLUMNS ARE REQUIRED
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


# NUMPY RANDOM GENERATORS

In [20]:
# IF WE WANT TO GENERATE RANDOM NUMBERS IN SAME ORDER , THEN WE HAVE TO USE SEED , SUPPOSE 1ST NUMBER IS 47 THEN IT WILL GENERATE ELEMENTS IN THE SOME ORDER WHUICH WILL BE REALTED TO 47
np.random.seed(1)

In [21]:
a = np.arange(10)
print(a)
a = np.arange(10) + 5
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [22]:
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [23]:
# THIS RETURNS VALUES FROM A STANDARD NORMAL DISTRIBUTIONS
a=np.random.rand(2,3) # 2,3 IS SHAPE
print(a)

a=np.random.randint(5,10,3)
print()
print(a)

# RANDOMLY PICK ONE ELEMENT FROM AN ARRAY
element = np.random.choice([1,4,5,2,3,6,78,87,8,7])
print(element)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]

[9 7 9]
5


# STATISTICAL FUNCTIONS IN numpy

In [28]:
a = np.array([[1,2,13,14],[15,23,12,96]])
print(a)
print()
print(np.min(a))
print(np.max(a))
print()
print(np.min(a,axis = 0)) # MINIMUM ALONG THE COLUMNS

[[ 1  2 13 14]
 [15 23 12 96]]

1
96

[ 1  2 12 14]


In [29]:
print(np.max(a,axis = 1))

[14 96]


In [32]:
# CALCULATION OF MEAN
m=sum(a)/8
print(m)
print()
print(np.mean(a,axis = 1))
print(np.mean(a,axis = 0))

[ 2.     3.125  3.125 13.75 ]

[ 7.5 36.5]
[ 8.  12.5 12.5 55. ]


In [33]:
# CALCULATION OF MEADIAN
print(np.median(a))

13.5


# MEAN VS AVERAGE , AVERAGE IS WEIGHTED , IN CASE OF AVERAGE EVERY ELEMENT IS MULTIPLIED BY THEIR RESPECTIOVE WEIGHS THEN THERE AVERAGE IS TAKEN.

In [34]:
c= np.array([1,5,4,2,0])
print(np.mean(c))

2.4


In [35]:
wts = np.array([1,2,3,4,5])
print(np.average(c,weights = wts)) # WEIGHTS PARAMETER IS GIVEN I, SEE MEAN AND AVERAGE ARE DIFFERENT.

2.066666666666667


# STANDARD DEVIATION

In [38]:
u= np.mean(c)
std = np.sqrt(np.mean(abs(c-u)**2))
print(std)
print()
print(np.std(c)) # std IS THE INBUILT FUNCTION FOR CALCULATION OF STANDARD DEVIATION


1.854723699099141

1.854723699099141


# VARIANCE - SQUARE OF STANDARD DEVIATION

In [40]:
print(std**2)
print()
print(np.var(c)) # var IS THE INBUILT FUNCTION IN numpy FOR CALCULATION OF VARIANCE

3.440000000000001

3.4400000000000004
