In [1]:
import numpy as np

In [2]:
input_size = 3 # number of features
layers = [4,3] # NUmber of neurons in the first and the second layer
output_size = 2

# Defining a Neural Network 

In [13]:
# Defining softmax helper function
def softmax(a):
    """Softmax is a function that does e^a(i)/sum(e^a(i)) , suppose a=[1,2,3] then its softmax would be e^1/(e^1+e^2+e^3) , 
    e^2/(e^1+e^2+e^3), e^3/(e^1+e^2+e^3). Here we can see that the sum is going to be 1 for all the values that we have we have 
    calculated so far.
    """
    e_pa = np.exp(a) # numpy does broadcasting for a vector so e_pa is a vector
    ans = e_pa/np.sum(e_pa,axis=1,keepdims=True) # axis is 0 for colums which is by default and axis 1 is for rows. Keepdims explained below
    return ans

a = np.array([[10,10],[20,20]])
a_ = softmax(a)
print(a_)

[[0.5 0.5]
 [0.5 0.5]]


In [8]:
a = np.array([[1,2,3],[6,5,4]])
print(np.sum(a)) # This would give us the sum of all the elements in the 2d vector.
print(np.sum(a,axis=0)) # Sum of all the columns
print(np.sum(a,axis=1)) # Sum of all the elements along the row
# Now keepdims just preservs the shape of the array
print(np.sum(a,axis=0,keepdims=True)) # This would return thr sum along the columns in a 2d vector

21
[7 7 7]
[ 6 15]
[[7 7 7]]


In [3]:
class NeuralNetwork():
    def __init__(self,input_size,output_size):
        np.random.seed(0)
        
        model = {}
        
        # First Layer
        model['w1'] = np.random.randn(input_size,layers[0]) #this would generate a normal distribution.
        model['b1'] = np.zeros((1,layers[0]))
        
        #Second Layer
        model['w2'] = np.random.randn(layers[0],layers[1]) 
        model['b2'] = np.zeros((1,layers[1]))
        
        #Third Layer/Output layer
        model['w3'] = np.random.randn(layers[1],output_size) 
        model['b3'] = np.zeros((1,output_size))
        
        self.model=model
        
        
    # Defining forward propagation
    def forward(self,x):
        
        W1,W2,W3 = self.model['W1'],self.model['W2'],self.model['W3']
        b1,b2,b3 = self.model['b1'],self.model['b2'],self.model['b3']
        
        z1 = np.dot(x,W1)+b1
        a1 = np.tanh(z1) # tanh is a function like sigmoid as it converts any input in range -1 to 1, sigmoid does in range 0 and 1
        
        z2 = np.dot(a1,W2)+b2
        a2 = np.tanh(z2)
        
        z3 = np.dot(a2,W3)+b3
        y_ = softmax(z3)
        

In [4]:
weg = np.random.randn(input_size,layers[0])
print(weg)

[[-1.33385865  1.40719915 -1.83330746  1.31613022]
 [-0.69709161 -1.02259691  0.4585747   1.85202931]
 [-0.468795    1.02537599 -0.97798401  0.82079649]]
